mx6-camera-objs := mx6-camif.o mx6-encode.o mx6-preview.o

obj-$(CONFIG_VIDEO_IMX6_CAMERA) += mx6-camera.o
obj-$(CONFIG_IMX6_MIPI_CSI2) += mipi-csi2.o
obj-$(CONFIG_IMX6_CAMERA_OV5640_MIPI) += ov5640-mipi.o
obj-$(CONFIG_IMX6_CAMERA_OV5642) += ov5642.o
obj-$(CONFIG_IMX6_CAMERA_ADV7180) += adv7180.o
